theme: jekyll-theme-minimal

title: [Oskars Niks Mālnieks]
description: [Economics & Finance | Data Science]

google_analytics: [G-SGFRRVR6H2]
google_analytics: [UA-194942531-1]

search: true

#logo: [oskarsniks.github.io/portrait.jpeg]
#logo: [portrait.jpeg]
logo: [/main/root/ONM.PNG]


